---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chs.
--- DateTime: 18-12-14 下午4:48
--- 存档数据

gamedata = {}
--玩家共享信息
gamedata.is_loaded = false
--获胜者 0平局 1玩家1 2玩家2
gamedata.winner = 0
--轮次
gamedata.turn = 1
--是否执子
gamedata.is_keepchess = false
--当前鼠标子位
gamedata.now_mpoint = 0
--当前执子的原始位置
gamedata.last_point = 0
--当前执子
gamedata.last_type = 0
--错误执子位置
gamedata.error_point = 0
--上次错误时间点纪录，仅提示一秒
gamedata.last_error_time = 0
--实时棋盘数据
gamedata.PAN_RUN = {

}


