---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chs.
--- DateTime: 19-1-7 下午3:10
--- 预加载游戏数据和资源，并提供给 eventer 和 painter使用

require('gdata.gamedata')
require('gdata.basedata')
require('core.love_engine')
loader = {}
--静态资源
loader.RESOURCE = {
    --title_m = love_engine.audio.newSource("resource/media/title.mp3", "stream"),
    p1_img = love_engine.graphics.newImage("resource/uis/p1.png"),
    p2_img = love_engine.graphics.newImage("resource/uis/p2.png"),
    togo_img = love_engine.graphics.newImage("resource/uis/togo.png"),
    error_img = love_engine.graphics.newImage("resource/uis/error.png"),
    fire_img = love_engine.graphics.newImage("resource/uis/fire.png")

}
--初始场景
loader.SCENE_STATUS = {
    cur_scene = basedata.SCENE_CODE.TITLE.code,
}
--字体
loader.FONT_TYPE = {
    MSYH17 = love_engine.graphics.newFont("resource/font/msyh.TTF",17),--字体文件一定要支持中文，这里使用【微软雅黑】
    MSYH34 = love_engine.graphics.newFont("resource/font/msyh.TTF",34)--字体文件一定要支持中文，这里使用【微软雅黑】
}


