---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chs.
--- DateTime: 19-1-7 下午3:10
--- 预加载游戏数据和资源，并提供给 eventer 和 painter使用

require('gdata.gamedata')
require('gdata.basedata')
require('core.love_engine')
loader = {}
--静态资源
loader.RESOURCE = {
    --音频媒体素材
    bgm_m = love_engine.audio.newSource("resource/media/bgm.mp3", "stream"),
    bomb_m = love_engine.audio.newSource("resource/media/bomb.mp3", "stream"),
    jump_m = love_engine.audio.newSource("resource/media/jump.mp3", "stream"),
    win_m = love_engine.audio.newSource("resource/media/win.mp3", "stream"),
    error_m = love_engine.audio.newSource("resource/media/error.mp3", "stream"),
    --图片素材
    p1_img= love_engine.graphics.newImage("resource/uis/p1.png"),
    p2_img = love_engine.graphics.newImage("resource/uis/p2.png"),
    togo_img = love_engine.graphics.newImage("resource/uis/togo.png"),
    error_img = love_engine.graphics.newImage("resource/uis/error.png"),
    fire_img = love_engine.graphics.newImage("resource/uis/fire.png"),
    p1win_img = love_engine.graphics.newImage("resource/uis/p1win.jpg"),
    p2win_img = love_engine.graphics.newImage("resource/uis/p2win.jpg")
}
--初始场景
loader.SCENE_STATUS = {
    cur_scene = basedata.SCENE_CODE.TITLE.code,
}
--字体
loader.FONT_TYPE = {
    MSYH17 = love_engine.graphics.newFont("resource/font/msyh.TTF",17),--字体文件一定要支持中文，这里使用【微软雅黑】
    MSYH34 = love_engine.graphics.newFont("resource/font/msyh.TTF",34)--字体文件一定要支持中文，这里使用【微软雅黑】
}


