---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chs.
--- DateTime: 18-12-14 下午4:05
---
--预加载资源
require('core.love_engine')
require('loader')
require('painter')
require('eventer')
local utf8 = require("utf8")
--添加全局即时器，用于处理动画效果
local game_timer = 0

function love.load()
    --游戏初始化，先校验存档文件是否存在
    last_saving_data = love_engine.filesystem.read('gamedata.txt',all)
    if last_saving_data == nil then
        --若无存档文件，则加载title_nosave页面,
        loader.SCENE_STATUS.cur_scene=basedata.SCENE_CODE.TITLE.code
        basedata.SCENE_CODE.TITLE.is_save=false
    else
        --若文档存在，则加载title界面。
        loader.SCENE_STATUS.cur_scene=basedata.SCENE_CODE.TITLE.code
        basedata.SCENE_CODE.TITLE.is_save=true
    end
    --捕捉鼠标相关信息
    mouse_left_clicked = false
    mouse_right_clicked = false
    is_left_click = false
    is_right_click = false

    -- enable key repeat so backspace can be held down to trigger love.keypressed multiple times.
    love.keyboard.setKeyRepeat(true)

end

--更新函数
function love.update(dt)
    game_timer = game_timer+dt
    cur_mouse_x = love_engine.mouse.getX()
    cur_mouse_y = love_engine.mouse.getY()
    --基础的鼠标单击判断方式
    if love_engine.mouse.isDown("1") then
        mouse_left_clicked = true
    else
        if mouse_left_clicked ==true then
            mouse_left_clicked =false
            is_left_click = true
        end
    end

    if love_engine.mouse.isDown("2") then
        mouse_right_clicked = true
    else
        if mouse_right_clicked ==true then
            mouse_right_clicked =false
            is_right_click = true
        end
    end
    --执行更新事件
    eventer.dojob(loader.SCENE_STATUS.cur_scene,cur_mouse_x,cur_mouse_y,is_left_click,is_right_click,game_timer)
    --重置参数
    is_left_click = false
    is_right_click = false

end


--画布
function love.draw()
    --根据场景持续作画
    painter.dojob(loader.SCENE_STATUS.cur_scene,cur_mouse_x,cur_mouse_y,game_timer)
end


